# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - dev
 
variables:
  Major: 1
  Minor: 0
  Patch: 1
  packageVersion: '$(Major).$(Minor).$(Patch).$(Build.BuildId)'
  proj: $(System.TeamProjectId)
  feed: CarFunctions
  workingDirectory: '$(System.DefaultWorkingDirectory)/CarFunctions.Infrastructure'
  vmImageName: 'windows-2019'

jobs:
  - job: Create package
    displayName: Create package
    pool:
      vmImage: $(vmImageName)

    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET 6 Core sdk'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(workingDirectory)/*.csproj'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'packageVersion'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet push'
      inputs:
        command: push
        feedPublish: '$(proj)/$(feed)'